spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: service-consumer
          uri: lb://service-consumer
          predicates:
            # 匹配路径转发
            - Path=/consumer/**
          filters:
            - RewritePath=/consumer(?<segment>/?.*), $\{segment}

        - id: service-provider
          uri: lb://service-provider
          predicates:
            # 匹配路径转发
            - Path=/provider/**
          filters:
            - RewritePath=/provider(?<segment>/?.*), $\{segment}

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 端口号
server:
  port: 8888
